import React, { useState, useEffect, useCallback } from 'react';

import AppLayout from '../components/AppLayout';
import { BookCard } from '../components/BookCard';
import { useAuth } from '../context/AuthContext';
import { useFavorites } from '../context/FavoritesContext';
import { useReadingHistory } from '../context/ReadingHistoryContext';
import { recommendationService } from '../services/recommendationService';
import type { Book } from '../types';

const BookCardSkeleton = () => (
  <div className="glass-card rounded-2xl p-4 animate-pulse min-w-[200px]">
    <div className="w-full aspect-[2/3] bg-surface-container-highest rounded-xl mb-4" />
    <div className="h-4 bg-surface-container-highest rounded w-3/4 mb-2" />
    <div className="h-3 bg-surface-container-highest rounded w-1/2 mb-4" />
    <div className="h-8 bg-surface-container-highest rounded mb-2" />
    <div className="h-8 bg-surface-container-highest rounded" />
  </div>
);

const RecommendationRow: React.FC<{ title: string, books: Book[], loading: boolean }> = ({ title, books, loading }) => {
  if (!loading && books.length === 0) return null;

  return (
    <section className="mb-6 sm:mb-10">
      <div className="flex items-center justify-between mb-3 sm:mb-4 px-1">
        <h2 className="text-lg sm:text-xl font-bold font-display text-on-surface">{title}</h2>
      </div>
      <div className="flex overflow-x-auto gap-3 sm:gap-4 pb-4 snap-x snap-mandatory custom-scrollbar">
        {loading
          ? [0, 1, 2, 3, 4].map(i => <div key={i} className="snap-start w-[200px] sm:w-[240px] shrink-0"><BookCardSkeleton /></div>)
          : books.map(book => (
              <div key={book.id} className="snap-start w-[200px] sm:w-[240px] shrink-0">
                <BookCard book={book} />
              </div>
            ))
        }
      </div>
    </section>
  );
};

const Recommendations: React.FC = () => {
  const { user } = useAuth();
  const { favorites } = useFavorites();
  const { historyEntries } = useReadingHistory();

  const [loading, setLoading] = useState(true);
  const [personalized, setPersonalized] = useState<Book[]>([]);
  const [interests, setInterests] = useState<Book[]>([]);
  const [continueReading, setContinueReading] = useState<Book[]>([]);
  const [trending, setTrending] = useState<Book[]>([]);
  const [popular, setPopular] = useState<Book[]>([]);
  const [newest, setNewest] = useState<Book[]>([]);
  const [similarToFavs, setSimilarToFavs] = useState<Book[]>([]);
  const [readersAlsoLiked, setReadersAlsoLiked] = useState<Book[]>([]);
  const [recentlyViewed, setRecentlyViewed] = useState<Book[]>([]);
  const [highestRated, setHighestRated] = useState<Book[]>([]);

  const loadAll = useCallback(async () => {
    if (!user?.id) return;
    setLoading(true);
    try {
      const promises = [
        recommendationService.getPersonalized(12).then(setPersonalized),
        recommendationService.getByInterests(12).then(setInterests),
        recommendationService.getTrending(12).then(setTrending),
        recommendationService.getPopular(12).then(setPopular),
        recommendationService.getNewArrivals(12).then(setNewest),
        recommendationService.getHighestRated(12).then(setHighestRated)
      ];

      if (historyEntries.length > 0) {
        promises.push(recommendationService.getContinueReading(12).then(setContinueReading));
        promises.push(recommendationService.getRecentlyViewed(12).then(setRecentlyViewed));
        promises.push(recommendationService.getReadersAlsoLiked(12).then(setReadersAlsoLiked));
      } else {
        setContinueReading([]);
        setRecentlyViewed([]);
        setReadersAlsoLiked([]);
      }

      if (favorites.length > 0) {
        promises.push(recommendationService.getSimilarToFavorites(12).then(setSimilarToFavs));
      } else {
        setSimilarToFavs([]);
      }

      await Promise.all(promises);
    } catch (e) {
      console.error("Failed to load recommendations", e);
    } finally {
      setLoading(false);
    }
  }, [user?.id, historyEntries.length, favorites.length]);

  useEffect(() => {
    loadAll();
  }, [loadAll]);

  return (
    <AppLayout>
            <section className="mb-6 sm:mb-8">
              <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold mb-2 flex items-center gap-2 sm:gap-3 text-primary">
                <span className="material-symbols-outlined text-2xl sm:text-3xl" style={{ fontVariationSettings: "'FILL' 1" }}>auto_awesome</span>
                Recommended For You
              </h1>
              <p className="text-xs sm:text-sm text-on-surface-variant">
                Curated recommendations generated by our multi-strategy recommendation engine.
              </p>
            </section>

            <RecommendationRow title="✨ Top Personalized Picks" books={personalized} loading={loading} />
            <RecommendationRow title="📖 Continue Reading" books={continueReading} loading={loading} />
            <RecommendationRow title="🎯 Based on Your Interests" books={interests} loading={loading} />
            <RecommendationRow title="❤️ Similar to Your Favorites" books={similarToFavs} loading={loading} />
            <RecommendationRow title="🔥 Trending Now" books={trending} loading={loading} />
            <RecommendationRow title="👥 Readers Also Liked" books={readersAlsoLiked} loading={loading} />
            <RecommendationRow title="⭐ Highest Rated" books={highestRated} loading={loading} />
            <RecommendationRow title="👀 Recently Viewed" books={recentlyViewed} loading={loading} />
            <RecommendationRow title="🏆 Most Popular" books={popular} loading={loading} />
            <RecommendationRow title="🆕 New Arrivals" books={newest} loading={loading} />
    </AppLayout>
  );
};

export default Recommendations;
